<?php

$labels['autoreply'] = 'Autosvar';
$labels['changeautoreply'] = 'Ändra autosvar';

$labels['enabled'] = 'Aktiv';
$labels['subject'] = 'Ämne';
$labels['message'] = 'Meddelande';
$labels['expires'] = 'Förfaller';

$messages['successfullyupdated'] = 'Autosvaret har uppdaterats.';
$messages['internalerror'] = 'Kunde inte uppdatera autosvar.';
$messages['connecterror'] = $messages['internalerror'] . ' Uppkopplingsfel.';
$messages['loadinternalerror'] = 'Kunde inte ladda autosvar.';
$messages['loadconnecterror'] = $messages['loadinternalerror'] . ' Uppkopplingsfel.';
