<?php

$labels = array();

$labels['autoreply'] = 'Automatische Antwort';
$labels['changeautoreply'] = 'Automatische Antwort bearbeiten';

$labels['enabled'] = 'Aktiviert';
$labels['subject'] = 'Betreff';
$labels['message'] = 'Nachricht';
$labels['expires'] = 'Läuft ab';

$messages = array();
$messages['successfullyupdated'] = 'Automatische Antwort erfolgreich aktualisiert.';
$messages['internalerror'] = 'Fehler bei der ausgewählten Aktion.';
//$messages['connecterror'] = $messages['internalerror'] . ' Connection error.';
$messages['loaderror'] = 'Automatische Antwort konnte nicht geladen werden.';
$messages['loadconnecterror'] = $messages['loadinternalerror'] . ' Connection error.';
$messages['updateerror'] = 'Automatische Antwort konnte nicht aktualisiert werden.';
$messages['updateconnecterror'] = $messages['updateerror'] . ' Connection error.';
