<?php

$labels = array();

$labels['autoreply'] = 'Házon kívül';
$labels['changeautoreply'] = 'Házon kívül módosítása';

$labels['enabled'] = 'Bekapcsolás';
$labels['subject'] = 'Tárgy';
$labels['message'] = 'Üzenet';
$labels['expires'] = 'Lejár?';
$labels['expiresdate'] = 'Lejárat dátuma';

$messages = array();
$messages['successfullyupdated'] = 'Házon kívül sikeresen frissítésre került.';
$messages['internalerror'] = 'Hiba történt.';
//$messages['connecterror'] = $messages['internalerror'] . ' Connection error.';
$messages['loaderror'] = 'Házon kívül betöltési hiba.';
$messages['loadconnecterror'] = $messages['loadinternalerror'] . ' Connection error.';
$messages['updateerror'] = 'Házon kívül frissítési hiba.';
$messages['updateconnecterror'] = $messages['updateerror'] . ' Connection error.';
