<?php

$labels['autoreply'] = 'Autosvar';
$labels['changeautoreply'] = 'Ändra autosvar';

$labels['enabled'] = 'Aktiv';
$labels['subject'] = 'Ämne';
$labels['message'] = 'Meddelande';
$labels['expires'] = 'Förfaller';
$labels['expiresdate'] = 'Förfallodatum';

$messages['successfullyupdated'] = 'Autosvaret har uppdaterats.';
$messages['internalerror'] = 'Fel uppstod i vald åtgärd.';
//$messages['connecterror'] = $messages['internalerror'] . ' Uppkopplingsfel.';
$messages['loaderror'] = 'Kunde inte ladda autosvar.';
$messages['loadconnecterror'] = $messages['loadinternalerror'] . ' Uppkopplingsfel.';
$messages['updateerror'] = 'Kunde inte uppdatera autosvar.';
$messages['updateconnecterror'] = $messages['updateerror'] . ' Connection error.';
